# Python (data science) - NumPy

_Mikołaj Leszczuk_


W tej części skupimy się na technikach przetwarzania danych w Pythonie. Nauczymy się wczytywać dane z różnych źródeł, przechowywać je w pamięci komputera i wykonywać na nich różnego rodzaju operacje. Dane na których przyjdzie nam pracować będą pochodzić z różnych źródeł i mogą reprezentować dokumenty, obrazy, dźwięki, wyniki pomiarów, wydarzenia w czasie i wszystko inne co można w pewien sposób zapisać.

Na pierwszy rzut oka może wydawać się, że nie jest możliwe reprezentowanie tak różnych danych w spójny sposób. Okazuje się jednak, że większość danych z jakimi mamy styczność można przedstawić za pomocą macierzy liczbowych - np. zdjęcie w komputerze jest zapisane jako kilkuwymiarowa macierz liczb które oznaczają kolory poszczególnych pikseli.

Aby skutecznie analizować dane zwykle będziemy dążyć aby przedstawić je w formie numerycznej.

Narzędzia na których się skupimy to dwa pakiety Pythonowe:
- NumPy (Numerical Python)
- Pandas

# Przetwarzanie danych w Pythonie - NumPy

![](https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg)

## NumPy

NumPy pozwala nam efektywnie przechowywać i operować na dużych zbiorach danych. NumPy leży zwykle u podstaw wszystkich innych technik i narzędzi związanych z data science, więc czas poświęcony na naukę NumPy na pewno zwróci się w przyszłości. Jest to jedna z pierwszych bibliotek, z którymi chcemy się zaznajomić, pracując przy analizie danych oraz sztucznej inteligencji. Jest to biblioteka składająca się z wielowymiarowych obiektów tablicowych i zbioru procedur do przetwarzania tych tablic. Za jej można wykonywać operacje matematyczne i logiczne na tablicach.

## Dlaczego używać NumPy?

- NumPy jest szybki, ponieważ napisany jest w języku C oraz C++ które są językami kompilowanymi (aby uzyskać działający program musi on zostać uprzednio skompilowany do postaci kodu maszynowego - do postaci binarnej) ale częściowo jest też napisany w Python, który jest językiem interpretowanym,
- w Pythonie mamy listy, które służą do celów tablic, ale ich przetwarzanie jest wolne, dzięki NumPy mamy dostarczony obiekt tablicy, który jest 50 razy szybszy od tradycyjnych list Pythonowych,
- obiekt tablicy w NumPy nazywa się `ndarray`, zapewnia on wiele funkcji pomocniczych, które bardzo ułatwiają pracę z tymi tablicami,
- tablice NumPy są przechowywane w jednym ciągłym miejscu w pamięci, w przeciwieństwie do list Pythonowych, dzięki czemu procesy mogą uzyskiwać do nich dostęp i bardzo efektywnie nimi manipulować,
- NumPy jest biblioteką Open Source, czyli każdy może zobaczyć jej kod i przyczynić się do jego rozwoju.

In [1]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install --upgrade numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 1.7 MB/s  0:00:031.7 MB/s eta 0:00:01:01
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 2.4.4 which is incompatible.
agh-vqis 3.4.6 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.4.4 which is incompatible.
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
print(np.__version__)

2.4.4


### Typy danych w Pythonie i w NumPy

Python sam w sobie jest językiem który dynamicznie typowanym, co oznacza, że Python sam potrafi rozpoznawać typy obiektów z których korzystamy. Rozważmy np Pythonową listę:


In [4]:
l = [1, "2", True, 3.0, None]

In [5]:
[type(item) for item in l]

[int, str, bool, float, NoneType]

Jak widać Python potrafi samemu rozpoznać typy obiektów i stworzyć listę która zawiera obiektu różnego typu.
Ta elastyczność ma jednak swoją cenę - każdy obiekt w liście musi przechowywać informacje o swoim typie. 

Z perspektywy dużych zbiorów danych dużo efektywniej jest przechowywać dane w postaci wektorów wcześniej określonego typu. NumPy dostarcza nam właśnie tego typu kontener, który nazywa się `Array`.

In [6]:
# tablica liczb całkowitych
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [7]:
# tablica liczb zmiennoprzecinkowych
np.array([4.1, 0, 1, 2, 3])

array([4.1, 0. , 1. , 2. , 3. ])

Zauważ, że obiekty typu `int` zostały zamienione przez NumPy na typ `float` aby zachować spójność typu w tablicy.

Ponadto w odróżnieniu do Pythonowych list, NumPy z łatwością reprezentuje również tablice wielowymiarowe:

In [8]:
print(np.array([range(i, i + 3) for i in [2, 4, 6]]))

[[2 3 4]
 [4 5 6]
 [6 7 8]]


### Sposoby tworzenia tablic w NumPy

In [14]:
# 10 elementowa tablica wypełniona zerami
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Tablica o wymiarach 5x3, wypełniona 1.
np.ones((5, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# Tablica wypełniona ciągiem liniowym z krokiem 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# Tablica o wymiarach 3x3 z wartościami wylosowanymi z rozkładu N(0, 1)
np.random.normal(0, 1, (3, 3))

array([[ 0.63091408,  2.02720904,  0.47673218],
       [-1.71031911, -1.58010487,  0.02338562],
       [ 2.46650376,  0.54212893, -1.16488023]])

In [25]:
# Tablica o wymiarach 4x5 z liczbami całkowitymi wylosowanymi z przedziału [0, 10)
np.random.randint(0, 10, (4, 5))

array([[7, 0, 9, 8, 1],
       [3, 7, 0, 9, 8],
       [9, 1, 1, 8, 5],
       [0, 8, 0, 3, 9]])

NumPy posiada dużo więcej typów danych niż Python, aby przeczytać o wszystkich możliwościach warto zajrzęć do dokumentacji:
https://numpy.org/doc/stable/user/basics.types.html

### Operowanie na tablicach w NumPy 

Skupimy się teraz na operacjach jakie można wykonywać na NumPy tablicach. Zobaczymy między innymi jak:

- Odczytywać i ustawiać pojedyncze elementy w tablicy
- Sprawdzać rozmiar, typ, użycie pamięci tablicy
- Tworzyć tablice jako wycinki większych tablic
- Zmieniać wymiary tablicy
- Łączyć i dzielić tablice

Zacznijmy od stworzenia trzy wymiarowej tablicy wypełnionej liczbami całkowitymi:

In [28]:
# Trzy wymiarowa tablica o wymiarach 2x3x4 
# z losowymi liczbami całkowitymi z przedziału [0, 100)
x = np.random.randint(100, size=(2, 3, 4))

In [29]:
x

array([[[27, 90, 56, 62],
        [75, 47, 72, 95],
        [15,  0, 95, 65]],

       [[ 5, 68, 66, 17],
        [87, 30, 19, 37],
        [23, 57, 81, 61]]])

In [30]:
print(f"x ndim: {x.ndim}")  # liczba wymiarów
print(f"x shape: {x.shape}")  # wymiary tablicy
print(f"x size: {x.size}")  # całkowity rozmiar tablicy

x ndim: 3
x shape: (2, 3, 4)
x size: 24


In [31]:
print(f"x dtype: {x.dtype}")  # typ danych przechowywanych w tablicy

x dtype: int64


In [32]:
print(f"itemsize: {x.itemsize} bytes")  # rozmiar jednego elementu
print(f"nbytes: {x.nbytes} bytes")  # rozmiar całej tablicy (itemsize x size)

itemsize: 8 bytes
nbytes: 192 bytes


Indeksowanie tablic w NumPy jest bardzo podobne do tego w Pythonie, odwołanie do i-tej wartości (licząc od zera) odbywa się poprzez użycie nawiasów kwadratowych:

In [33]:
y = np.arange(0, 10)

In [34]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
y[5]

np.int64(5)

In [36]:
y[0]

np.int64(0)

Tak jak w standardowym Pythonie, możemy korzystać z ujemnych indeksów:

In [37]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
y[-1]

np.int64(9)

Wielowymiarowe tablice możemy indeksować za pomocą krotek:

In [39]:
x

array([[[27, 90, 56, 62],
        [75, 47, 72, 95],
        [15,  0, 95, 65]],

       [[ 5, 68, 66, 17],
        [87, 30, 19, 37],
        [23, 57, 81, 61]]])

In [40]:
x[0, 1, 2]  # odczytanie elementu o współrzednych (0,1,2)

np.int64(72)

W ten sam sposób możemy również modyfikować elementy:

In [41]:
x

array([[[27, 90, 56, 62],
        [75, 47, 72, 95],
        [15,  0, 95, 65]],

       [[ 5, 68, 66, 17],
        [87, 30, 19, 37],
        [23, 57, 81, 61]]])

In [42]:
x[0, 1, 2] = 42

In [43]:
x

array([[[27, 90, 56, 62],
        [75, 47, 42, 95],
        [15,  0, 95, 65]],

       [[ 5, 68, 66, 17],
        [87, 30, 19, 37],
        [23, 57, 81, 61]]])

Możemy również używać _slice_ aby odwołać się do wycinka tabeli:

In [44]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
y[:5]  # pierwsze 5 elementów

array([0, 1, 2, 3, 4])

In [46]:
y[4:7:2]  # wycinek ze środka tablicy

array([4, 6])

In [47]:
y[::-1]  # tablica odczytana od tyłu

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Podobnie możemy korzystać ze _slice_ aby wycinać kawałki wielowymiarowych tablic:

In [48]:
x

array([[[27, 90, 56, 62],
        [75, 47, 42, 95],
        [15,  0, 95, 65]],

       [[ 5, 68, 66, 17],
        [87, 30, 19, 37],
        [23, 57, 81, 61]]])

In [49]:
x[:1, :, :3]  # dwukropek bez argumentów oznacza wybranie wszystkich elementów z danego wymiaryu!

array([[[27, 90, 56],
        [75, 47, 42],
        [15,  0, 95]]])

Warto tutaj zaznaczyć, że w przeciwieństwie do działania na liście w Pythonie, gdzie użycie _slice_ zwraca nam kopie w NumPy otrzymujemy _view_.

In [50]:
# Python
l1 = [1, 2, 3]
l2 = l1[2:]
l2[0] = 4
print(l1)  # l1 pozostaje nie zmienione!
print(l2)  # l1 pozostaje nie zmienione!

[1, 2, 3]
[4]


In [51]:
# NumPy
x1 = np.array([1, 2, 3])
x2 = x1[2:]
x2[0] = 4
print(x1)  # x1 i x2 reprezentują tą samą tablicę!
print(x2)  # x1 i x2 reprezentują tą samą tablicę!

[1 2 4]
[4]


Jeżeli chcemy otrzymać kopię tablicy, musimy użyć metody `copy()`

In [52]:
# NumPy
x1 = np.array([1, 2, 3])
x2 = x1[2:].copy()
x2[0] = 4
print(x1)  # x1 i x2 reprezentują tą samą tablicę!
print(x2)  # x1 i x2 reprezentują tą samą tablicę!

[1 2 3]
[4]


### Zmiana wymiarów tablicy

Zmiana wymiarów tablicy odbywa się poprzez użycie metody `reshape`, powiedzmy, że chcemy ułożyć liczby od 1 do 9 w tablicy 3x3:

In [54]:
np.arange(1, 10).reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Często będzie nam się przydawać możliwość zmienienia jednowymiarowego wektora w dwuwymiarowy:

In [57]:
x = np.array([1, 2, 3])
print(x)
print(x.reshape((1, 3))) # dwuwymiarowa tablica z jednym wierszem i trzema kolumnami
print(x.reshape((3, 1))) # dwuwymiarowa tablica z trzema wierszami i jedną kolumną

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


### Łączenie tablic

Do łączenia tablic możemy korzystać z funkcji takich jak:
- `np.concatenate`
- `np.vstack`
- `np.hstack`

In [60]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

Podobnie dla dwuwymiarowych tablic:


In [61]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(np.concatenate([grid, grid]))
print(np.concatenate([grid, grid], axis=1))  # łączenie wzdłuż drugiego wymiaru

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


`np.vstack` i `np.hstack` są skrótami do operacji łączenia pionowo i poziomo:

In [62]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

print(np.vstack([x, grid]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [63]:
y = np.array([[99],
              [99]])

print(np.hstack([grid, y]))

[[ 9  8  7 99]
 [ 6  5  4 99]]


Przeciwieństwiem łączenia jest dzielenie i mamy tu do dyspozycji funkcję `np.split`

Korzystając ze `np.split` musimy podać indeksy w których tablica ma być "przecięta".

In [65]:
x = np.arange(10)
print(x)
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)  # zauważ, że dwa punkty dzielenia tworzą trzy tablice

[0 1 2 3 4 5 6 7 8 9]
[0 1 2] [3 4] [5 6 7 8 9]


### Wykonywanie obliczeń na tablicach

Nauczymy się teraz wykonywać obliczenia na tablicach NumPy. Aby działania które wykonujemy były wykonywane efektywnie będziemy musieli zmienić nasze podejście do tego w jaki sposób myślimy o niektórych operacjach. Poznamy operacje wektorowe, które pozwolą nam pisać kod który wykonuje się szybko i sprawnie.

Rozważmy funkcję wyliczającą odwrotności elementów w tablicy:

In [66]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i, value in enumerate(values):
        output[i] = 1.0 / value
    return output

In [67]:
values = np.random.randint(1, 10, size=5)

In [68]:
values

array([7, 1, 4, 6, 5])

In [69]:
compute_reciprocals(values)

array([0.14285714, 1.        , 0.25      , 0.16666667, 0.2       ])

Spróbujmy wykonąć tą samą operację dla bardzo dużej tablicy:

In [70]:
big_array = np.random.randint(1, 100, size=1_000_000)

„%timeit” to magiczna funkcja, gdzie kod składa się z jednej linii lub powinien być napisany w tej samej linii, aby zmierzyć czas wykonania. To polecenie wielokrotnie wykonuje dostępny kod i zwraca najszybszy wynik. Obliczy ono automatycznie liczbę wykonań potrzebnych do kodu w całkowitym oknie wykonania wynoszącym 2 sekundy.

In [71]:
%timeit compute_reciprocals(big_array)

413 ms ± 7.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Wykonanie tej operacji dla miliona elementów zajęło pół sekundy! Jest to absurdalnie wolno biorąc pod uwagę obecne możliwości komputerów. Ta powolność jest spowodowana tym w jaki sposób działa Python - wykonując pojedynczą operację dla każdego elementu Python musi wykonać wiele działań w tle związanych z określaniem typu.

Dla większości operacji NumPy pozwala nam korzystać z wbudowanych funkcji które wykonają się w sposób zwektoryzowany:

In [72]:
%timeit 1.0 / big_array  # ta sama operacja wykonana w sposób wektorowy

356 μs ± 1.03 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


W ten sposób możemy wykonywać wszystkie podstawowe operacje na tablicach:

In [75]:
x = np.arange(4)
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)
print("-x     =", -x)
print("x ** 2 =", x ** 2)
print("x % 2  =", x % 2)

x      = [0 1 2 3]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 2  = [0 2 4 6]
x / 2  = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


### Agregacje na tablicach

NumPy oferuje nam wiele wbudowanych funkcji do wyliczania najczęściej stosowanych agregacji na danych:

In [77]:
L = np.random.random(100)
print(L)
print(np.sum(L), np.min(L), np.max(L))

[0.91933793 0.20097547 0.81707339 0.38660326 0.46842323 0.75209531
 0.51215526 0.31970181 0.6450529  0.19700799 0.28968566 0.17332965
 0.46634756 0.12399284 0.42575188 0.08014296 0.74696626 0.86851727
 0.27984628 0.34224084 0.13168122 0.67527276 0.75891402 0.2382793
 0.47871565 0.93809939 0.2922666  0.68511481 0.21772505 0.8216773
 0.82732585 0.48036217 0.33248093 0.67259032 0.7760115  0.94352258
 0.6018611  0.90445391 0.62892439 0.80066863 0.14027487 0.82854034
 0.26231806 0.81926988 0.53107527 0.12757555 0.97679105 0.73996438
 0.74479691 0.81666177 0.23096073 0.5214227  0.17275547 0.90331721
 0.4337185  0.47387572 0.33096876 0.92000633 0.64586407 0.56159974
 0.69459471 0.57867278 0.36819761 0.06276607 0.40175873 0.58322701
 0.18019495 0.33470724 0.0813584  0.55629286 0.69254223 0.46773384
 0.25828729 0.41904374 0.30745584 0.83195922 0.174133   0.40568918
 0.38565257 0.41850454 0.29282387 0.19186091 0.78575652 0.98770811
 0.83382547 0.10445716 0.63692588 0.14134552 0.8628741  0.529588

Warto zwrócić uwagę, że korzystanie z funkcji NumPy jest dużo szybsze niż z wbudowanych funkcji Pythonowych:

In [78]:
%timeit np.sum(L)
%timeit sum(L)

760 ns ± 3.53 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.83 μs ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Agregacje możemy wykonywać również po poszczególnych wymiarach:

In [79]:
M = np.random.randint(10, size=(3, 4))
print(M)

[[0 3 8 7]
 [8 8 1 3]
 [3 3 7 8]]


In [80]:
print(M.sum(axis=0))
print(M.sum(axis=1))
print(M.min(axis=0))
print(M.min(axis=1))

[11 14 16 18]
[18 20 21]
[0 3 1 3]
[0 1 3]


### Porównywanie, maski

Stosując operator porównania na tablicy zawsze otrzymamy nową tablicę zawierającą typ `bool`.

In [81]:
x = np.array([1, 2, 3, 4, 5])

In [82]:
x < 3

array([ True,  True, False, False, False])

In [83]:
x > 3

array([False, False, False,  True,  True])

In [84]:
x == 3

array([False, False,  True, False, False])

Tablice wartości logicznych często przydają się w kombinacji z innymi funkcjami np:

In [85]:
x = np.random.randint(10, size=(4, 4))

In [86]:
x

array([[2, 5, 0, 1],
       [6, 2, 5, 3],
       [5, 5, 9, 7],
       [0, 8, 6, 6]])

In [87]:
x < 6

array([[ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False, False],
       [ True, False, False, False]])

In [91]:
# Ile wartości w tablicy jest mniejszych niż 6?
np.count_nonzero(x < 6)

np.int64(10)

In [92]:
# Ile wartości w każdej kolumnie jest mniejsze niż 6?
np.sum(x < 6, axis=0)

array([3, 3, 2, 2])

In [93]:
# Czy jest wartość mniejsza niż 0?
np.any(x < 0)

np.False_

Tablic logicznych możemy również używać jako masek do wybierania wartości z tablicy które spełniają określone warunki:

In [94]:
x

array([[2, 5, 0, 1],
       [6, 2, 5, 3],
       [5, 5, 9, 7],
       [0, 8, 6, 6]])

In [95]:
x < 5

array([[ True, False,  True,  True],
       [False,  True, False,  True],
       [False, False, False, False],
       [ True, False, False, False]])

In [96]:
x[x < 5]  # Elementy z x które są mniejsze niż 5

array([2, 0, 1, 2, 3, 0])

### Fancy indexing

Fancy indexing polega na przekazywaniu tablicy indeksów aby otrzymać wiele elementów tablicy na raz. 

In [97]:
x = np.random.randint(100, size=10)

In [98]:
print(x)

[38 76 33 22 38 40  2 75 68  4]


Jeżeli chcemy wybrać 3., 7. i 2. element możemy to zrobić na dwa sposoby:

In [99]:
# Sposób pierwszy
[x[3], x[7], x[2]]

[np.int64(22), np.int64(75), np.int64(33)]

In [100]:
# Fancy indexing
ind = [3, 7, 2]
x[ind]

array([22, 75, 33])

Kiedy korzystamy z fancy indexingu wymiary tablicy wynikowej są takie jak tablicy indeksów:

In [101]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[22, 75],
       [38, 40]])

Rodzaje indeksowań można ze sobą mieszać:

In [102]:
x = np.random.randint(100, size=(5, 5))

In [103]:
x

array([[88, 83, 97, 38, 94],
       [94, 26, 38, 72, 82],
       [88, 98, 20, 62,  5],
       [69, 79, 69, 99,  1],
       [38, 48, 47, 93, 17]])

In [104]:
x[2, [0, 1, 2]]

array([88, 98, 20])

In [105]:
x[1:, [2, 0, 1]]

array([[38, 94, 26],
       [20, 88, 98],
       [69, 69, 79],
       [47, 38, 48]])

### Sortowanie tablic

NumPy ma również swoje wbudowane funkcje służące do sortowania tablic:

In [106]:
x = np.random.randint(100, size=5)

In [107]:
x

array([43, 56, 74, 48,  4])

In [108]:
np.sort(x)

array([ 4, 43, 48, 56, 74])

Sortowanie można również przeprowadzić w miejscu:

In [109]:
x

array([43, 56, 74, 48,  4])

In [110]:
x.sort()

In [111]:
x

array([ 4, 43, 48, 56, 74])

Istnieje również funkcja `np.argsort` która zwraca indeksy posortowanych elementów:

In [112]:
x = np.random.randint(100, size=5)

In [113]:
x

array([72, 42, 39, 88, 28])

In [114]:
i = np.argsort(x)

In [115]:
i

array([4, 2, 1, 0, 3])

In [116]:
x[i]  # Fancy indexing daje nam posortowaną tablicę

array([28, 39, 42, 72, 88])

## Ćwiczenia NumPy

Pełny zestaw ćwiczeń do wykorzystania na zajęciach lub po zajęciach.



## **A. Podstawy NumPy (Zadania 1–22)**



1. Utwórz tablicę liczb całkowitych od 0 do 19.  
   Następnie zmodyfikuj jej typ danych na float32.  
   Sprawdź minimalną i maksymalną wartość w tablicy.

#### Rozwiązanie

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(20)         # 0..19
arr1_float = arr1.astype(np.float32)

print("Tablica:", arr1_float)
print("dtype:", arr1_float.dtype)
print("Min:", arr1_float.min(), "Max:", arr1_float.max())


Tablica: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
dtype: float32
Min: 0.0 Max: 19.0


2. Skorzystaj z funkcji `linspace`, aby stworzyć tablicę 1D z 6 równomiernie rozmieszczonymi punktami w zakresie [0, 3].  
   Upewnij się, że liczba elementów zgadza się z parametrem `num`.


#### Rozwiązanie

In [3]:
arr2 = np.linspace(0, 3, 6)
print(arr2)
print("Liczba elementów:", len(arr2))

[0.  0.6 1.2 1.8 2.4 3. ]
Liczba elementów: 6




3. Z tablicy liczb (np. 0–19) utwórz tablicę 2D o kształcie (4, 5) przy pomocy metody `reshape`.  
   Sprawdź nowy kształt (`.shape`) i liczbę wymiarów (`.ndim`).


#### Rozwiązanie

In [4]:
arr3 = np.arange(20)
arr3_2d = arr3.reshape(4, 5)
print(arr3_2d)
print("Kształt:", arr3_2d.shape, "Liczba wymiarów:", arr3_2d.ndim)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Kształt: (4, 5) Liczba wymiarów: 2


4. Rozszerz tablicę 2D (4×5) do wymiaru 3D (np. 2×2×5).  
   Następnie użyj `ravel()` i `flatten()`, aby spłaszczyć powstałą tablicę.  
   Zwróć uwagę, które z tych metod tworzą kopię, a które widok.

#### Rozwiązanie

In [5]:
arr4_2d = np.arange(20).reshape(4, 5)     # 4×5
arr4_3d = arr4_2d.reshape(2, 2, 5)       # 2×2×5

raveled = arr4_3d.ravel()    # może dawać widok
flattened = arr4_3d.flatten()# kopia

print("3D shape:", arr4_3d.shape)
print("ravel shape:", raveled.shape)
print("flatten shape:", flattened.shape)

3D shape: (2, 2, 5)
ravel shape: (20,)
flatten shape: (20,)




5. Utwórz tablicę 1D z wartościami 10–19.  
   Wyświetl element o indeksie 0, element o indeksie 5 i element o indeksie -1.

#### Rozwiązanie

In [6]:
arr5 = np.arange(10, 20)
print("Element 0:", arr5[0])
print("Element 5:", arr5[5])
print("Element -1:", arr5[-1])

Element 0: 10
Element 5: 15
Element -1: 19


6. Stwórz tablicę 2D (5×5) z losowymi liczbami całkowitymi (`random.randint`).  
   Wybierz:
   - cały 2. wiersz (indeks 1),
   - 3 pierwsze kolumny wiersza 4 (indeks 3),
   - podtablicę (2×2) z górnego lewego rogu.

#### Rozwiązanie

In [7]:
arr6 = np.random.randint(0, 100, size=(5, 5))
print("Oryginalna tablica:\n", arr6)

print("Cały 2. wiersz:", arr6[1, :])
print("3 pierwsze kolumny wiersza 4:", arr6[3, :3])
print("Podtablica 2x2 z lewego górnego rogu:\n", arr6[0:2, 0:2])

Oryginalna tablica:
 [[11 43  8 82 17]
 [90 50 38 17 28]
 [87 93 25 15 16]
 [85 57 64 44 70]
 [27 22 16 31 41]]
Cały 2. wiersz: [90 50 38 17 28]
3 pierwsze kolumny wiersza 4: [85 57 64]
Podtablica 2x2 z lewego górnego rogu:
 [[11 43]
 [90 50]]





7. Utwórz tablicę z wartościami `[0, 10, 20, 30, 40, 50]`.  
   Wybierz co drugi element, zaczynając od indeksu 1 (otrzymasz 10, 30, 50).


#### Rozwiązanie

In [8]:
arr7 = np.array([0, 10, 20, 30, 40, 50])
result7 = arr7[1::2]
print("Wynik:", result7)

Wynik: [10 30 50]




8. W tablicy 2D (5×5) ustaw cały 3. wiersz (indeks 2) na wartość 99.  
   Wyświetl zmodyfikowaną tablicę.

#### Rozwiązanie

In [9]:
arr8 = np.random.randint(0, 50, size=(5, 5))
print("Przed:\n", arr8)

arr8[2, :] = 99
print("Po:\n", arr8)

Przed:
 [[36 36 35  3  9]
 [ 9  1 33 42 29]
 [44 32 35 14  5]
 [ 5 21 27 37 19]
 [20  0 38  1 40]]
Po:
 [[36 36 35  3  9]
 [ 9  1 33 42 29]
 [99 99 99 99 99]
 [ 5 21 27 37 19]
 [20  0 38  1 40]]




9. Korzystając z maski logicznej, wszystkie elementy < 10 w powyższej tablicy zastąp wartością 10.  
   Porównaj efekt z oryginałem.

#### Rozwiązanie

In [10]:
arr9 = np.random.randint(0, 20, size=(5, 5))
print("Przed:\n", arr9)

mask9 = arr9 < 10
arr9[mask9] = 10
print("Po:\n", arr9)

Przed:
 [[11  2 18  0  8]
 [ 8 16  5 10 11]
 [12 16  1 15 12]
 [ 2  7  3  9  0]
 [11  9 16  0 18]]
Po:
 [[11 10 18 10 10]
 [10 16 10 10 11]
 [12 16 10 15 12]
 [10 10 10 10 10]
 [11 10 16 10 18]]






10. Przytnij wszystkie wartości > 90 do poziomu 90 (można użyć maski lub funkcji `clip`).


#### Rozwiązanie

In [11]:
arr10 = np.random.randint(80, 100, size=(4, 4))
print("Przed:\n", arr10)

arr10_clipped = np.clip(arr10, a_min=None, a_max=90)
print("Po:\n", arr10_clipped)

Przed:
 [[93 88 98 87]
 [96 89 80 93]
 [82 84 96 81]
 [87 97 96 84]]
Po:
 [[90 88 90 87]
 [90 89 80 90]
 [82 84 90 81]
 [87 90 90 84]]


11. Stwórz tablicę 2D (3×3).  
    Dodaj nowy wiersz (3-elementowy) do jej końca, korzystając np. z funkcji `vstack`.  
    Wyświetl wynik.

#### Rozwiązanie

In [12]:
arr11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Przed:\n", arr11)

new_row = np.array([10, 11, 12])
arr11_v = np.vstack([arr11, new_row])
print("Po:\n", arr11_v)

Przed:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Po:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



12. Do powstałej tablicy dodaj nową kolumnę (4. kolumnę) za pomocą funkcji `hstack`.  
    Upewnij się, że nowa kolumna ma wymiar (4, 1), jeżeli tablica ma teraz 4 wiersze.


#### Rozwiązanie

In [13]:

arr12 = arr11_v
new_col = np.array([[100],[200],[300],[400]])  # kształt (4,1)

arr12_h = np.hstack([arr12, new_col])
print("Po dodaniu kolumny:\n", arr12_h)


Po dodaniu kolumny:
 [[  1   2   3 100]
 [  4   5   6 200]
 [  7   8   9 300]
 [ 10  11  12 400]]


13. Użyj funkcji `delete`, aby usunąć 2. kolumnę (indeks 1).  
    Sprawdź kształt tablicy przed i po usunięciu.


#### Rozwiązanie

In [14]:

arr13 = arr12_h
print("Przed:\n", arr13)

arr13_del = np.delete(arr13, 1, axis=1)
print("Po usunięciu kolumny o indeksie 1:\n", arr13_del)


Przed:
 [[  1   2   3 100]
 [  4   5   6 200]
 [  7   8   9 300]
 [ 10  11  12 400]]
Po usunięciu kolumny o indeksie 1:
 [[  1   3 100]
 [  4   6 200]
 [  7   9 300]
 [ 10  12 400]]


14. Stwórz tablicę 2D (3×4) z liczbami od 1 do 12.  
    Policz sumę wszystkich elementów oraz sumy wzdłuż wierszy (axis=1) i wzdłuż kolumn (axis=0).

#### Rozwiązanie

In [15]:

arr14 = np.arange(1, 13).reshape(3, 4)
print("Tablica:\n", arr14)
print("Suma wszystkich:", arr14.sum())
print("Suma wzdłuż wierszy (axis=1):", arr14.sum(axis=1))
print("Suma wzdłuż kolumn (axis=0):", arr14.sum(axis=0))


Tablica:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Suma wszystkich: 78
Suma wzdłuż wierszy (axis=1): [10 26 42]
Suma wzdłuż kolumn (axis=0): [15 18 21 24]


15. Oblicz średnią (`mean`) i medianę (`median`) w tablicy 2D (np. (3×4) z poprzedniego zadania).  
    Porównaj wyniki.


#### Rozwiązanie

In [ ]:

arr15 = arr14
print("Średnia:", arr15.mean())
print("Mediana:", np.median(arr15))


16. Napisz krótką funkcję (bez pętli), która w sposób wektorowy podniesie każdą wartość w tablicy 1D do kwadratu.


#### Rozwiązanie

In [ ]:

def square_elements(x):
    return x**2

arr16 = np.array([2, 3, 4])
print("Oryginał:", arr16)
print("Kwadrat:", square_elements(arr16))



17. Skorzystaj z `cumsum` (cumulative sum) i `cumprod` (cumulative product) na tablicy `[1, 2, 3, 4]`.  
    Wyświetl wyniki.

#### Rozwiązanie

In [ ]:

arr17 = np.array([1,2,3,4])
print("cumsum:", np.cumsum(arr17))
print("cumprod:", np.cumprod(arr17))



18. Wygeneruj tablicę 10 liczb losowych (typu float) w przedziale [0..1].  
    Oblicz odchylenie standardowe (`std`) oraz wariancję (`var`).

#### Rozwiązanie

In [ ]:

arr18 = np.random.rand(10)
print("Tablica:", arr18)
print("std:", arr18.std(), "var:", arr18.var())



19. Stwórz tablicę 2D (3×3) oraz jednowymiarową (3 elementy).  
    Dodaj je do siebie, korzystając z mechanizmu broadcastingu.

#### Rozwiązanie

In [ ]:

mat19 = np.arange(9).reshape(3,3)
vec19 = np.array([1,2,3])

res19 = mat19 + vec19  # Broadcasting
print("macierz:\n", mat19)
print("wektor:", vec19)
print("wynik:\n", res19)




20. Zademonstruj przypadek, w którym broadcasting się nie powiedzie (np. (3×3) + (2×3)).  
    Zaobserwuj komunikat o błędzie.

#### Rozwiązanie

In [ ]:

mat20 = np.zeros((3,3))
mat20b = np.zeros((2,3))

# Odkomentować, aby zobaczyć błąd:
# res20 = mat20 + mat20b
# print(res20)

print("Broadcasting nie zadziała, bo kształty (3,3) i (2,3) są niekompatybilne.")


21. Wygeneruj tablicę losową (8 elementów).  
    Użyj funkcji `where`, aby elementy < 0.5 zastąpić 0, a >= 0.5 zastąpić 1.  
    Wyświetl wynik.

#### Rozwiązanie

In [ ]:

arr21 = np.random.rand(8)
res21 = np.where(arr21 < 0.5, 0, 1)
print("Oryginał:", arr21)
print("Po where:", res21)


22. Stwórz dwie tablice 1D (każda po 5 elementów).  
    Sklej je w jedną tablicę za pomocą `concatenate` i posortuj wynik za pomocą `sort`.

#### Rozwiązanie

In [ ]:

a22 = np.array([5,2,9,1,10])
b22 = np.array([7,3,8,6,4])

c22 = np.concatenate([a22, b22])
c22_sorted = np.sort(c22)
print("Po sklejeniu:", c22)
print("Po posortowaniu:", c22_sorted)


---

## **B. Dalsze Techniki NumPy (Zadania 23–29)**

23. Stwórz tablicę 2D (np. 100 wierszy, 3 kolumny) z losowymi wartościami float.  
    Policz korelację między kolumnami, korzystając z funkcji `corrcoef`.

#### Rozwiązanie

In [ ]:

arr23 = np.random.rand(100, 3)
corr = np.corrcoef(arr23.T)
print("Macierz korelacji:\n", corr)


24. W tej samej tablicy oblicz minimum, maksimum oraz kwartyle (funkcja `percentile` dla 25%, 50%, 75%).


#### Rozwiązanie

In [ ]:

arr24 = arr23
print("Min:", arr24.min())
print("Max:", arr24.max())
q25 = np.percentile(arr24, 25)
q50 = np.percentile(arr24, 50)
q75 = np.percentile(arr24, 75)
print("25%:", q25, "50% (median):", q50, "75%:", q75)


25. Stwórz tablicę 2D (5×5) z losowymi liczbami.  
    Posortuj ją wzdłuż kolumn (parametr `axis=0`), np. korzystając z metody `sort`.


#### Rozwiązanie

In [ ]:

arr25 = np.random.randint(0, 100, (5, 5))
print("Przed sortowaniem:\n", arr25)

arr25.sort(axis=0)  # Sortuje w miejscu wzdłuż kolumn
print("Po sortowaniu (axis=0):\n", arr25)




26. Podziel tablicę 1D (10 elementów) na dwie równe części, używając funkcji `split`.  
    Wyświetl obie części.


#### Rozwiązanie

In [ ]:

arr26 = np.arange(10)
part1, part2 = np.split(arr26, 2)
print("Oryginalna:", arr26)
print("Część 1:", part1)
print("Część 2:", part2)


27. Załóż, że masz tablicę 1D (20 elementów).  
    Wybierz elementy mniejsze niż 5 **lub** większe niż 15, stosując złożoną maskę (np. `(arr < 5) | (arr > 15)`).


#### Rozwiązanie

In [ ]:

arr27 = np.random.randint(0, 20, 20)
mask27 = (arr27 < 5) | (arr27 > 15)
result27 = arr27[mask27]
print("Oryginał:", arr27)
print("Wybrane (mask):", result27)


28. Użyj funkcji `clip`, aby przyciąć wartości w tej samej tablicy do przedziału [5..15].  
    Wyświetl efekt.


#### Rozwiązanie

In [ ]:

arr28 = np.random.randint(0, 20, 10)
clipped28 = np.clip(arr28, 5, 15)
print("Przed:", arr28)
print("Po clip [5..15]:", clipped28)


29. Stwórz dwie tablice 1D (każda po 5 elementów).  
    Sklej je (funkcja `concatenate`) i posortuj wynik (`sort`).  
    Porównaj z zadaniem 22, gdzie również występowało łączenie i sortowanie.


#### Rozwiązanie

In [ ]:

a29 = np.array([10, 1, 7, 3, 2])
b29 = np.array([4, 9, 5, 8, 6])

merged29 = np.concatenate([a29, b29])
sorted29 = np.sort(merged29)

print("Sklejone:", merged29)
print("Posortowane:", sorted29)


## **C. Zadania z Obrazami (Zadania 30–44)**


Mamy wczytane trzy obrazy  do tablic NumPy:  
- *The Persistence of Memory (1931)* – Salvador Dalí  
- *Flying Ship* – Zdzisław Beksiński  
- *Girl before a Mirror* – Pablo Picasso  

Każdy obraz to tablica o kształcie (wysokość, szerokość, kanały), np. `dali_img`, `beksinski_img`, `picasso_img`.

#### Rozwiązanie

In [ ]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt


dali_img = mpimg.imread('images/dali.jpg')
beksinski_img = mpimg.imread('images/beksinski.jpg')
picasso_img = mpimg.imread('images/picasso.jpg')

print("Wczytano obrazy")





30. Wyświetl kształt (`shape`), liczbę kanałów (ostatni element `.shape`) i typ danych (`dtype`) w tablicach: `dali_img`, `beksinski_img`, `picasso_img`.

#### Rozwiązanie

In [ ]:

print("dali_img shape:", dali_img.shape, "channels:", dali_img.shape[2], "dtype:", dali_img.dtype)
print("beksinski_img shape:", beksinski_img.shape, "channels:", beksinski_img.shape[2], "dtype:", beksinski_img.dtype)
print("picasso_img shape:", picasso_img.shape, "channels:", picasso_img.shape[2], "dtype:", picasso_img.dtype)



31. Za pomocą narzędzi do wykresów (np. `matplotlib.pyplot`) wyświetl wszystkie trzy obrazy obok siebie, używając funkcji `subplot`.  
    Dodaj tytuły, aby je rozróżnić.

#### Rozwiązanie

In [ ]:

fig, axs = plt.subplots(1, 3, figsize=(12, 4))

axs[0].imshow(dali_img)
axs[0].set_title("Dalí")
axs[0].axis('off')

axs[1].imshow(beksinski_img)
axs[1].set_title("Beksiński")
axs[1].axis('off')

axs[2].imshow(picasso_img)
axs[2].set_title("Picasso")
axs[2].axis('off')

plt.tight_layout()
plt.show()



32. Oblicz średnią wartość kanału R, G i B w obrazie Dalí.  
    Zdecyduj, który kanał ma największą średnią.

#### Rozwiązanie

In [ ]:
dali_img[:,:, 0].shape

In [ ]:
mean_r = dali_img[..., 0].mean()


In [ ]:


# dali_img ma shape (wys, szer, 3)
mean_r = dali_img[:,:, 0].mean()
mean_g = dali_img[..., 1].mean()
mean_b = dali_img[..., 2].mean()

print("Dalí - mean R:", mean_r, "mean G:", mean_g, "mean B:", mean_b)

# Sprawdzenie, który największy:
channels_means = {'R': mean_r, 'G': mean_g, 'B': mean_b}
max_channel = max(channels_means, key=channels_means.get)
print("Największa średnia w kanale:", max_channel)


33. Sprawdź minimalną i maksymalną wartość pikseli (dla kanałów R, G, B) w obrazie Beksińskiego (np. metodami `.min()` i `.max()`).


#### Rozwiązanie

In [ ]:

min_r_bek = beksinski_img[..., 0].min()
max_r_bek = beksinski_img[..., 0].max()
min_g_bek = beksinski_img[..., 1].min()
max_g_bek = beksinski_img[..., 1].max()
min_b_bek = beksinski_img[..., 2].min()
max_b_bek = beksinski_img[..., 2].max()

print("Beksiński:")
print("R min:", min_r_bek, "R max:", max_r_bek)
print("G min:", min_g_bek, "G max:", max_g_bek)
print("B min:", min_b_bek, "B max:", max_b_bek)



34. Rozdziel obraz Picassa na trzy osobne tablice kanałów (R, G, B), używając indeksowania (np. `[..., 0]`).  
    Następnie zrekonstruuj oryginalny obraz przy pomocy `dstack` i wyświetl efekt.

#### Rozwiązanie

In [ ]:

pic_r = picasso_img[..., 0]
pic_g = picasso_img[..., 1]
pic_b = picasso_img[..., 2]

reconstructed_pic = np.dstack([pic_r, pic_g, pic_b])

# Wyświetlamy oryginał i zrekonstruowany
fig, (ax1, ax2) = plt.subplots(1,2, figsize=(8,4))
ax1.imshow(picasso_img)
ax1.set_title("Oryginał Picasso")
ax1.axis('off')

ax2.imshow(reconstructed_pic)
ax2.set_title("Zrekonstruowany")
ax2.axis('off')

plt.show()


35. Napisz funkcję `to_grayscale(img)`, która tworzy obraz w skali szarości według formuły `0.299*R + 0.587*G + 0.114*B`.  
    Zastosuj ją do obrazu Dalí i wyświetl wynik.


#### Rozwiązanie

In [ ]:

def to_grayscale(img):
    # img: (H, W, 3) 
    r = img[...,0]
    g = img[...,1]
    b = img[...,2]
    gray = 0.299*r + 0.587*g + 0.114*b
    return gray

dali_gray = to_grayscale(dali_img)
print(dali_gray.shape)
plt.imshow(dali_gray, cmap='gray')
plt.title("Dalí - Grayscale")
plt.axis('off')
plt.show()



36. W obrazie Beksińskiego zwiększ intensywność kanału R o 20% i przytnij wartości do maksymalnego poziomu (np. 255).  
    Porównaj efekt z oryginałem.


#### Rozwiązanie

In [ ]:

# Sprawdzamy dtype:
print("Beksiński dtype:", beksinski_img.dtype)

beks_modified = beksinski_img.copy().astype(np.float32)  # Pracujemy w float
beks_modified[..., 0] *= 1.2  # R * 1.2
beks_modified[..., 0] = np.clip(beks_modified[..., 0], 0, 255)

beks_modified = beks_modified.astype(np.uint8)

# Wyświetlenie oryginału vs modyfikacja:
fig, (ax1, ax2) = plt.subplots(1,2, figsize=(8,4))
ax1.imshow(beksinski_img)
ax1.set_title("Oryginał")
ax1.axis('off')

ax2.imshow(beks_modified)
ax2.set_title("R +20%")
ax2.axis('off')

plt.show()


37. Z obrazu Dalí wytnij fragment (np. `dali_img[50:300, 100:400, :]`) i wyświetl ten wykadrowany fragment.  
    Sprawdź nowy kształt tablicy.

#### Rozwiązanie

In [ ]:

dali_cropped = dali_img[50:300, 100:400, :]  # zależy od wymiarów faktycznych
print("Oryginał kształt:", dali_img.shape)
print("Wykadrowany kształt:", dali_cropped.shape)

plt.imshow(dali_cropped)
plt.title("Dalí - fragment")
plt.axis('off')
plt.show()



38. Zmniejsz obraz Beksińskiego dwukrotnie w obu wymiarach, korzystając z indeksowania co 2 piksele .  
    Wyświetl pomniejszony obraz.

#### Rozwiązanie

In [ ]:

beks_small = beksinski_img[::2, ::2, :]
print("Oryginał:", beksinski_img.shape, "Pomniejszony:", beks_small.shape)

plt.imshow(beks_small)
plt.title("Beksiński - pomniejszony")
plt.axis('off')
plt.show()



39. Odwróć obraz Picassa w poziomie (np. `flip` z parametrem `axis=1`).  
    Zapisz wynik do pliku `.npy` (funkcja `save`), a następnie wczytaj go ponownie (`load`), aby sprawdzić, czy zapis przebiegł poprawnie.


#### Rozwiązanie

In [ ]:

pic_flipped = np.flip(picasso_img, axis=1)

# Zapis do .npy:
np.save('picasso_flipped.npy', pic_flipped)

# Odczyt:
loaded_flipped = np.load('picasso_flipped.npy')

# Sprawdzenie:
fig, (ax1, ax2) = plt.subplots(1,2, figsize=(8,4))
ax1.imshow(picasso_img)
ax1.set_title("Oryginał")
ax1.axis('off')

ax2.imshow(loaded_flipped)
ax2.set_title("Flipped, wczytany z pliku .npy")
ax2.axis('off')

plt.show()




40. Obróć obraz Dalí o 90 stopni (np. w prawo), korzystając z `transpose` i ewentualnie `flip`.  
    Wyświetl wynik.

#### Rozwiązanie

In [ ]:

# Sposób 1: transpose + flip w poziomie
dali_rot = np.transpose(dali_img, (1, 0, 2))
dali_rot = np.flip(dali_rot, axis=0)

plt.imshow(dali_rot)
plt.title("Dalí - obrócony o 90° w prawo")
plt.axis('off')
plt.show()



41. Skonwertuj obraz Beksińskiego do skali szarości (funkcja z zadania 35).  
    Następnie utwórz maskę logiczną dla pikseli, których jasność jest mniejsza niż 100,  
    i zamień te piksele w oryginalnym obrazie kolorowym na [0, 0, 255] (np. intensywny niebieski).

#### Rozwiązanie

In [ ]:

beks_gray = to_grayscale(beksinski_img)  # używamy funkcji z zad. 35
beks_color_mod = beksinski_img.copy()

mask41 = beks_gray < 100
beks_color_mod[mask41] = [0, 0, 255]

fig, (ax1, ax2) = plt.subplots(1,2, figsize=(8,4))
ax1.imshow(beksinski_img)
ax1.set_title("Oryginał")
ax1.axis('off')

ax2.imshow(beks_color_mod)
ax2.set_title("Maska (<100) -> niebieski")
ax2.axis('off')

plt.show()





42. W obrazie Picassa przytnij wartości pikseli do zakresu [50..200], korzystając z `clip`.  
    Zaobserwuj zmianę kontrastu i wyświetl efekt.

#### Rozwiązanie

In [ ]:

pic_clipped = np.clip(picasso_img, 50, 200)

fig, (ax1, ax2) = plt.subplots(1,2, figsize=(8,4))
ax1.imshow(picasso_img)
ax1.set_title("Oryginał")
ax1.axis('off')

ax2.imshow(pic_clipped)
ax2.set_title("Clip [50..200]")
ax2.axis('off')

plt.show()



43. Jeżeli Dalí i Beksiński mają różne rozmiary, przytnij któryś z nich, by dopasować wymiary (liczbę wierszy i kolumn).  
    Następnie sklej je w poziomie (`hstack`) i wyświetl otrzymany „dwupanelowy” obraz.

#### Rozwiązanie

In [ ]:

dali_h, dali_w, _ = dali_img.shape
beks_h, beks_w, _ = beksinski_img.shape

min_h = min(dali_h, beks_h)
min_w = min(dali_w, beks_w)

dali_cropped2 = dali_img[:min_h, :min_w, :]
beks_cropped2 = beksinski_img[:min_h, :min_w, :]

combined = np.hstack([dali_cropped2, beks_cropped2])
print("combined shape:", combined.shape)

plt.imshow(combined)
plt.title("Dalí + Beksiński")
plt.axis('off')
plt.show()


44. Wybierz dowolny przetworzony obraz (np. po filtrze, kadrowaniu lub maskowaniu) i zapisz go w formacie PNG (np. przy pomocy `imsave` z `matplotlib`).  
    Otwórz plik poza Pythonem, aby sprawdzić poprawność zapisu.

#### Rozwiązanie

In [ ]:

# Załóżmy, że zapiszemy pic_clipped z zad. 42:
plt.imsave("picasso_clipped.png", pic_clipped)

# Plik powinien pojawić się w tym samym folderze lub możemy podać ścieżkę.
print("Zapisano plik 'picasso_clipped.png'. Otwórz poza Pythonem, aby sprawdzić.")
